// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// hungarian
IntegerVector hungarian(NumericMatrix cost);
RcppExport SEXP _mascarade_hungarian(SEXP costSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type cost(costSEXP);
    rcpp_result_gen = Rcpp::wrap(hungarian(cost));
    return rcpp_result_gen;
END_RCPP
}
// buildBoxFit
SEXP buildBoxFit(List polysx, List polysy);
RcppExport SEXP _mascarade_buildBoxFit(SEXP polysxSEXP, SEXP polysySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type polysx(polysxSEXP);
    Rcpp::traits::input_parameter< List >::type polysy(polysySEXP);
    rcpp_result_gen = Rcpp::wrap(buildBoxFit(polysx, polysy));
    return rcpp_result_gen;
END_RCPP
}
// radialCandidates
DataFrame radialCandidates(SEXP boxfit, NumericMatrix poi, NumericVector hw, NumericVector hh, double pad, double xlo, double xhi, double ylo, double yhi, int ndir, double step, double rstart, double rmax, double intfill, double dedup);
RcppExport SEXP _mascarade_radialCandidates(SEXP boxfitSEXP, SEXP poiSEXP, SEXP hwSEXP, SEXP hhSEXP, SEXP padSEXP, SEXP xloSEXP, SEXP xhiSEXP, SEXP yloSEXP, SEXP yhiSEXP, SEXP ndirSEXP, SEXP stepSEXP, SEXP rstartSEXP, SEXP rmaxSEXP, SEXP intfillSEXP, SEXP dedupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type boxfit(boxfitSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type poi(poiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hw(hwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hh(hhSEXP);
    Rcpp::traits::input_parameter< double >::type pad(padSEXP);
    Rcpp::traits::input_parameter< double >::type xlo(xloSEXP);
    Rcpp::traits::input_parameter< double >::type xhi(xhiSEXP);
    Rcpp::traits::input_parameter< double >::type ylo(yloSEXP);
    Rcpp::traits::input_parameter< double >::type yhi(yhiSEXP);
    Rcpp::traits::input_parameter< int >::type ndir(ndirSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< double >::type rstart(rstartSEXP);
    Rcpp::traits::input_parameter< double >::type rmax(rmaxSEXP);
    Rcpp::traits::input_parameter< double >::type intfill(intfillSEXP);
    Rcpp::traits::input_parameter< double >::type dedup(dedupSEXP);
    rcpp_result_gen = Rcpp::wrap(radialCandidates(boxfit, poi, hw, hh, pad, xlo, xhi, ylo, yhi, ndir, step, rstart, rmax, intfill, dedup));
    return rcpp_result_gen;
END_RCPP
}
// foreignLength
NumericVector foreignLength(NumericVector ex, NumericVector ey, NumericVector tx, NumericVector ty, IntegerVector lab, List polysx, List polysy);
RcppExport SEXP _mascarade_foreignLength(SEXP exSEXP, SEXP eySEXP, SEXP txSEXP, SEXP tySEXP, SEXP labSEXP, SEXP polysxSEXP, SEXP polysySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type lab(labSEXP);
    Rcpp::traits::input_parameter< List >::type polysx(polysxSEXP);
    Rcpp::traits::input_parameter< List >::type polysy(polysySEXP);
    rcpp_result_gen = Rcpp::wrap(foreignLength(ex, ey, tx, ty, lab, polysx, polysy));
    return rcpp_result_gen;
END_RCPP
}
// forcePolish
List forcePolish(SEXP boxfit, NumericVector cx0, NumericVector cy0, NumericVector hw, NumericVector hh, NumericVector tx, NumericVector ty, double pad, double xlo, double xhi, double ylo, double yhi, int iters, double step, double MU, double pad_tgt, double stepmin, bool ll_hard, bool sq);
RcppExport SEXP _mascarade_forcePolish(SEXP boxfitSEXP, SEXP cx0SEXP, SEXP cy0SEXP, SEXP hwSEXP, SEXP hhSEXP, SEXP txSEXP, SEXP tySEXP, SEXP padSEXP, SEXP xloSEXP, SEXP xhiSEXP, SEXP yloSEXP, SEXP yhiSEXP, SEXP itersSEXP, SEXP stepSEXP, SEXP MUSEXP, SEXP pad_tgtSEXP, SEXP stepminSEXP, SEXP ll_hardSEXP, SEXP sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type boxfit(boxfitSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cx0(cx0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cy0(cy0SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hw(hwSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type hh(hhSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< double >::type pad(padSEXP);
    Rcpp::traits::input_parameter< double >::type xlo(xloSEXP);
    Rcpp::traits::input_parameter< double >::type xhi(xhiSEXP);
    Rcpp::traits::input_parameter< double >::type ylo(yloSEXP);
    Rcpp::traits::input_parameter< double >::type yhi(yhiSEXP);
    Rcpp::traits::input_parameter< int >::type iters(itersSEXP);
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    Rcpp::traits::input_parameter< double >::type MU(MUSEXP);
    Rcpp::traits::input_parameter< double >::type pad_tgt(pad_tgtSEXP);
    Rcpp::traits::input_parameter< double >::type stepmin(stepminSEXP);
    Rcpp::traits::input_parameter< bool >::type ll_hard(ll_hardSEXP);
    Rcpp::traits::input_parameter< bool >::type sq(sqSEXP);
    rcpp_result_gen = Rcpp::wrap(forcePolish(boxfit, cx0, cy0, hw, hh, tx, ty, pad, xlo, xhi, ylo, yhi, iters, step, MU, pad_tgt, stepmin, ll_hard, sq));
    return rcpp_result_gen;
END_RCPP
}
// oneMoveSweep
IntegerVector oneMoveSweep(NumericVector cxmin, NumericVector cxmax, NumericVector cymin, NumericVector cymax, NumericVector ex, NumericVector ey, NumericVector tx, NumericVector ty, NumericVector len, List rows, IntegerVector init, int maxpass);
RcppExport SEXP _mascarade_oneMoveSweep(SEXP cxminSEXP, SEXP cxmaxSEXP, SEXP cyminSEXP, SEXP cymaxSEXP, SEXP exSEXP, SEXP eySEXP, SEXP txSEXP, SEXP tySEXP, SEXP lenSEXP, SEXP rowsSEXP, SEXP initSEXP, SEXP maxpassSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cxmin(cxminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cxmax(cxmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymin(cyminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymax(cymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type len(lenSEXP);
    Rcpp::traits::input_parameter< List >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type maxpass(maxpassSEXP);
    rcpp_result_gen = Rcpp::wrap(oneMoveSweep(cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass));
    return rcpp_result_gen;
END_RCPP
}
// twoMoveBnB
IntegerVector twoMoveBnB(NumericVector cxmin, NumericVector cxmax, NumericVector cymin, NumericVector cymax, NumericVector ex, NumericVector ey, NumericVector tx, NumericVector ty, NumericVector len, List rows, IntegerVector init, int maxpass, bool sq);
RcppExport SEXP _mascarade_twoMoveBnB(SEXP cxminSEXP, SEXP cxmaxSEXP, SEXP cyminSEXP, SEXP cymaxSEXP, SEXP exSEXP, SEXP eySEXP, SEXP txSEXP, SEXP tySEXP, SEXP lenSEXP, SEXP rowsSEXP, SEXP initSEXP, SEXP maxpassSEXP, SEXP sqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type cxmin(cxminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cxmax(cxmaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymin(cyminSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type cymax(cymaxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ex(exSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ey(eySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tx(txSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ty(tySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type len(lenSEXP);
    Rcpp::traits::input_parameter< List >::type rows(rowsSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type maxpass(maxpassSEXP);
    Rcpp::traits::input_parameter< bool >::type sq(sqSEXP);
    rcpp_result_gen = Rcpp::wrap(twoMoveBnB(cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass, sq));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mascarade_hungarian", (DL_FUNC) &_mascarade_hungarian, 1},
    {"_mascarade_buildBoxFit", (DL_FUNC) &_mascarade_buildBoxFit, 2},
    {"_mascarade_radialCandidates", (DL_FUNC) &_mascarade_radialCandidates, 15},
    {"_mascarade_foreignLength", (DL_FUNC) &_mascarade_foreignLength, 7},
    {"_mascarade_forcePolish", (DL_FUNC) &_mascarade_forcePolish, 19},
    {"_mascarade_oneMoveSweep", (DL_FUNC) &_mascarade_oneMoveSweep, 12},
    {"_mascarade_twoMoveBnB", (DL_FUNC) &_mascarade_twoMoveBnB, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_mascarade(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
