# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

hungarian <- function(cost) {
    .Call(`_mascarade_hungarian`, cost)
}

buildBoxFit <- function(polysx, polysy) {
    .Call(`_mascarade_buildBoxFit`, polysx, polysy)
}

radialCandidates <- function(boxfit, poi, hw, hh, pad, xlo, xhi, ylo, yhi, ndir, step, rstart, rmax, intfill, dedup) {
    .Call(`_mascarade_radialCandidates`, boxfit, poi, hw, hh, pad, xlo, xhi, ylo, yhi, ndir, step, rstart, rmax, intfill, dedup)
}

foreignLength <- function(ex, ey, tx, ty, lab, polysx, polysy) {
    .Call(`_mascarade_foreignLength`, ex, ey, tx, ty, lab, polysx, polysy)
}

oneMoveSweep <- function(cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass) {
    .Call(`_mascarade_oneMoveSweep`, cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass)
}

twoMoveBnB <- function(cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass, sq) {
    .Call(`_mascarade_twoMoveBnB`, cxmin, cxmax, cymin, cymax, ex, ey, tx, ty, len, rows, init, maxpass, sq)
}

